### ISSUE TITLE
BIG TODO

### ISSUE THREAD

**Issue by HackerKat** [LB31/ShintoPuzzleGame#77]
- [ ] neue FOnts für größeren text
- [x] refactor kami json
- [ ] refactor puzzle text json 
- [x] \n as spaces in json parserr implement
- [ ] game ende
- [x] susanno merge
- [x] audio, musik suche
- [x] drei kugel des lichts
- [x] spieler teleport zu susannoo
- [ ] bessere dialoge für alle Kamis und Yokais
- [ ] licht!! atmosphere finalisieren
- [x] tutorial merge
- [x] audio, musik einbauen
